In [1]:
import numpy as np
import pandas as pd

# mostly it will be used in the machine learning or deep learning classes and computer vision classes

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [11]:
6 + np.zeros((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [12]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
np.empty((3,4,6))

array([[[ 0.00000000e+000,  1.58101007e-322,  6.95325819e-310,
          4.94065646e-323,  5.43472210e-323, -6.51477233e+303],
        [             nan,              nan,  4.77772647e-299,
         -1.64460807e+284,  1.25252397e-311,  6.95325838e-310],
        [ 4.13661320e-280,  1.25252317e-311,  1.25252372e-311,
         -6.00036595e-210,  1.25252397e-311,  1.25252396e-311],
        [-5.81689430e+162,  1.25250838e-311,  6.95325838e-310,
         -6.31689286e+174,  1.25249015e-311,  6.95325837e-310]],

       [[ 6.35755729e+050,  1.25252397e-311,  6.95325838e-310,
         -2.54509738e-240,  1.25252397e-311,  1.25248886e-311],
        [-1.99444359e-227,  1.25252397e-311,  1.25248886e-311,
         -6.13252563e-197,  1.25249386e-311,  1.25248909e-311],
        [-5.97827990e+140,  1.25249191e-311,  6.95325837e-310,
          3.81224181e-117,  1.25251088e-311,  6.95325837e-310],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  

In [22]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [23]:
np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [33]:
np.linspace(2,6,100).reshape(50,2)

array([[2.        , 2.04040404],
       [2.08080808, 2.12121212],
       [2.16161616, 2.2020202 ],
       [2.24242424, 2.28282828],
       [2.32323232, 2.36363636],
       [2.4040404 , 2.44444444],
       [2.48484848, 2.52525253],
       [2.56565657, 2.60606061],
       [2.64646465, 2.68686869],
       [2.72727273, 2.76767677],
       [2.80808081, 2.84848485],
       [2.88888889, 2.92929293],
       [2.96969697, 3.01010101],
       [3.05050505, 3.09090909],
       [3.13131313, 3.17171717],
       [3.21212121, 3.25252525],
       [3.29292929, 3.33333333],
       [3.37373737, 3.41414141],
       [3.45454545, 3.49494949],
       [3.53535354, 3.57575758],
       [3.61616162, 3.65656566],
       [3.6969697 , 3.73737374],
       [3.77777778, 3.81818182],
       [3.85858586, 3.8989899 ],
       [3.93939394, 3.97979798],
       [4.02020202, 4.06060606],
       [4.1010101 , 4.14141414],
       [4.18181818, 4.22222222],
       [4.26262626, 4.3030303 ],
       [4.34343434, 4.38383838],
       [4.

In [34]:
np.linspace(2,6,100, endpoint= False).reshape(50,2)

array([[2.  , 2.04],
       [2.08, 2.12],
       [2.16, 2.2 ],
       [2.24, 2.28],
       [2.32, 2.36],
       [2.4 , 2.44],
       [2.48, 2.52],
       [2.56, 2.6 ],
       [2.64, 2.68],
       [2.72, 2.76],
       [2.8 , 2.84],
       [2.88, 2.92],
       [2.96, 3.  ],
       [3.04, 3.08],
       [3.12, 3.16],
       [3.2 , 3.24],
       [3.28, 3.32],
       [3.36, 3.4 ],
       [3.44, 3.48],
       [3.52, 3.56],
       [3.6 , 3.64],
       [3.68, 3.72],
       [3.76, 3.8 ],
       [3.84, 3.88],
       [3.92, 3.96],
       [4.  , 4.04],
       [4.08, 4.12],
       [4.16, 4.2 ],
       [4.24, 4.28],
       [4.32, 4.36],
       [4.4 , 4.44],
       [4.48, 4.52],
       [4.56, 4.6 ],
       [4.64, 4.68],
       [4.72, 4.76],
       [4.8 , 4.84],
       [4.88, 4.92],
       [4.96, 5.  ],
       [5.04, 5.08],
       [5.12, 5.16],
       [5.2 , 5.24],
       [5.28, 5.32],
       [5.36, 5.4 ],
       [5.44, 5.48],
       [5.52, 5.56],
       [5.6 , 5.64],
       [5.68, 5.72],
       [5.76,

In [ ]:
 ############## distance between two datasets and stepsize ############### 

In [35]:
np.linspace(2,6,100, endpoint= False, retstep= True)

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [36]:
np.logspace(1,2)

array([ 10.        ,  10.48113134,  10.98541142,  11.51395399,
        12.06792641,  12.64855217,  13.25711366,  13.89495494,
        14.56348478,  15.26417967,  15.9985872 ,  16.76832937,
        17.57510625,  18.42069969,  19.30697729,  20.23589648,
        21.20950888,  22.22996483,  23.29951811,  24.42053095,
        25.59547923,  26.82695795,  28.11768698,  29.47051703,
        30.88843596,  32.37457543,  33.93221772,  35.56480306,
        37.2759372 ,  39.06939937,  40.94915062,  42.9193426 ,
        44.98432669,  47.14866363,  49.41713361,  51.79474679,
        54.28675439,  56.89866029,  59.63623317,  62.50551925,
        65.51285569,  68.6648845 ,  71.9685673 ,  75.43120063,
        79.06043211,  82.86427729,  86.85113738,  91.0298178 ,
        95.40954763, 100.        ])

In [38]:
np.logspace(1,2,4, base=10)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [41]:
a=np.arange(16).reshape(4,4)

In [42]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
a=np.arange(32).reshape(4,4,2)

In [45]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [46]:
a.max()

31

In [47]:
a.max(axis=1)

array([[ 6,  7],
       [14, 15],
       [22, 23],
       [30, 31]])

In [48]:
10 + a

array([[[10, 11],
        [12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29],
        [30, 31],
        [32, 33]],

       [[34, 35],
        [36, 37],
        [38, 39],
        [40, 41]]])

In [49]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [50]:
a/0

<ipython-input-50-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0
<ipython-input-50-deacdc4ccabc>:1: RuntimeWarning: invalid value encountered in true_divide
  a/0


array([[[nan, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]],

       [[inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]],

       [[inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]],

       [[inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]]])

In [79]:
b = np.arange(1,26).reshape(5,5)

In [80]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
b = np.array(b)

In [82]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
c= b+10

In [84]:
c

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [85]:
d= b +5

In [86]:
d

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [87]:
c+d

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45],
       [47, 49, 51, 53, 55],
       [57, 59, 61, 63, 65]])

In [88]:
e = [4,4,4,4,4]

In [89]:
c+e

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [91]:
e = np.reshape(e , (5,1))
e

array([[4],
       [4],
       [4],
       [4],
       [4]])

In [92]:
c+e

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [93]:
x = np.array([1,2,3])

In [94]:
x

array([1, 2, 3])

In [95]:
y=x###############################3 SWALLOW COPY##############3 DATA NOT PERMANENTLY COPIED TO A NEW LOCATION#########

In [96]:
y

array([1, 2, 3])

In [97]:
z= np.copy(x) ####################################### DEEP COPY ##########################DATA PERMANENTLY TO NEW LOCATION

In [98]:
z

array([1, 2, 3])

In [99]:
x[0]=100

In [100]:
x

array([100,   2,   3])

In [101]:
y

array([100,   2,   3])

In [102]:
z

array([1, 2, 3])

In [ ]:
############################################## ID FUNCTION ################################################
# retrun the identity of an object
#

In [103]:
id(x)

2535191215536

In [104]:
id(y)

2535191215536

In [105]:
id(z)

2535185662768

In [106]:
id(x[0])

2535189442224

In [107]:
id(y[0])

2535189441744

In [108]:
id(z[0])

2535189442288

In [109]:
ad = np.array([45,68])

In [110]:
bd = ad

In [111]:
id(bd)

2535183996176

In [112]:
id(ad)

2535183996176

In [113]:
id(ad[0])

2535199687632

In [114]:
id(bd[0])

2535199688176

In [115]:
id(ad[1])

2535199687664

In [117]:
id(bd[1])

2535199689072

In [120]:
id(ad[0]) == id(bd[0])

True

In [121]:
id(ad[0]) == id(bd[1])

True

In [124]:
id(ad) == id(bd)

True

In [125]:
xt = np.array([34,56,96])

In [126]:
id(xt[0]) == id(ad[1])

True