# #NEW PACKAGE IN CASE DATA IS IN ARRAY OR MATRIX#
# #NUMPY ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::#
                                          #NUMERICAL PYTHON#
# ALL THE FUNCTIONS DERIEVED FROM THE MATLAB IN THE NUMPY 

In [2]:
import pandas as pd
import numpy as np


In [3]:
# what is array 
# arrays are equivalent to the list
# system understands everything as an array
#used in ml ,dl etc.


# what is matrix
# used in ml ,dl etc.


In [4]:
l= ["adviteeya", 1,2,3,4]

In [5]:
type(l)

list

In [ ]:
# How to convert list into array

In [10]:
np.array(l)

array(['adviteeya', '1', '2', '3', '4'], dtype='<U11')

In [ ]:
# When we the list in the array 

In [11]:
l1= ["advi", 1,2,3,4]

In [12]:
np.array(l1)

array(['advi', '1', '2', '3', '4'], dtype='<U11')

In [13]:
type(np.array(l1))

numpy.ndarray

In [ ]:
# What is the meaning of nd array
# n dimension 

In [14]:
np.array([3,4,5,6,7.0])

array([3., 4., 5., 6., 7.])

In [ ]:
# It has converted all the integer into floating point.
# By default it upcast to floating point

In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
# It will create this type of array 

In [16]:
type(np.array([[1,2],[3,4]]))

numpy.ndarray

In [17]:
a = np.array([[1,2],[3,4]])

In [ ]:
# data is stored in a row and column
#

In [18]:
a[0]

array([1, 2])

In [19]:
a[1]

array([3, 4])

In [20]:
a[1][1]

4

In [21]:
a[0][0]

1

In [22]:
a[0][1]

2

In [23]:
a[1][0]

3

In [24]:
a1 = np.array([3,4,5,6,7.0])

In [25]:
a1[0]

3.0

In [26]:
a1[2]

5.0

In [27]:
a1[4]

7.0

In [28]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
#  There is one parameter call ndmin

In [29]:
np.array([1,2,3,4,5], ndmin=0)

array([1, 2, 3, 4, 5])

In [30]:
np.array([1,2,3,4,5], ndmin=1)

array([1, 2, 3, 4, 5])

In [31]:
np.array([1,2,3,4,5], ndmin=2)

array([[1, 2, 3, 4, 5]])

In [32]:
np.array([1,2,3,4,5], ndmin=3)

array([[[1, 2, 3, 4, 5]]])

In [33]:
np.array([1,2,3,4,5], ndmin=4)

array([[[[1, 2, 3, 4, 5]]]])

In [ ]:
# dimension is increasing with ndmin aray within an array 
#Extract 1

In [34]:
a2 = np.array([1,2,3,4,5], ndmin=4)

In [ ]:
#Extract 1 from a2

In [35]:
a2[0]

array([[[1, 2, 3, 4, 5]]])

In [36]:
a2[0][0]

array([[1, 2, 3, 4, 5]])

In [37]:
a2[0][0][0]

array([1, 2, 3, 4, 5])

In [38]:
a2[0][0][0][0]

1

In [39]:
a2[0][0][0][1]

2

In [40]:
a2[0][0][0][2]

3

In [41]:
a2[0][0][0][3]

4

In [ ]:
# How data is stored actually 
# Number of brackets denotes the number of array dimension 

In [42]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
# npasarray

In [43]:
np.asanyarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [44]:
np.asarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [45]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
####################################### MATRIX################################################
# At minimum it is by default taking 2 dimension
# It is a 2-D element


In [46]:
np.mat([1,2,3,4,5,6])

matrix([[1, 2, 3, 4, 5, 6]])

In [47]:
b = [1,2,3,4,5,6,7,8,9]

In [48]:
np.asarray(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.mat(b)

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
np.asanyarray(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.asanyarray(np.mat(b))
# matrix is a child class of array
# as any array return the format of the array
# matrix is by default an array
# if it is matrix it will not convert

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
# from function returns the function responsible to generate any array
# at any point of time it will be array and matrix
# 

np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:

np.fromfunction(lambda i,j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [54]:

np.fromfunction(lambda i,j : i==j, (5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [55]:
np.fromfunction(lambda i,j : i!=j, (5,5))

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [ ]:
# Use of comparison operator

In [56]:
np.fromfunction(lambda i,j : i*j, (5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [57]:
np.fromfunction(lambda i,j : i*j, (5,5), dtype= int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [58]:
np.mat(np.fromfunction(lambda i,j : i*j, (5,5), dtype= int))

matrix([[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16]])

In [59]:
np.fromfunction(lambda i,j,k : i*j*k, (5,5,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16],
        [ 0,  6, 12, 18, 24],
        [ 0,  8, 16, 24, 32]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  3,  6,  9, 12],
        [ 0,  6, 12, 18, 24],
        [ 0,  9, 18, 27, 36],
        [ 0, 12, 24, 36, 48]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  4,  8, 12, 16],
        [ 0,  8, 16, 24, 32],
        [ 0, 12, 24, 36, 48],
        [ 0, 16, 32, 48, 64]]])

In [60]:
np.fromfunction(lambda i,j,k : i*j*k, (5,5,4), dtype= int)

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6],
        [ 0,  3,  6,  9],
        [ 0,  4,  8, 12]],

       [[ 0,  0,  0,  0],
        [ 0,  2,  4,  6],
        [ 0,  4,  8, 12],
        [ 0,  6, 12, 18],
        [ 0,  8, 16, 24]],

       [[ 0,  0,  0,  0],
        [ 0,  3,  6,  9],
        [ 0,  6, 12, 18],
        [ 0,  9, 18, 27],
        [ 0, 12, 24, 36]],

       [[ 0,  0,  0,  0],
        [ 0,  4,  8, 12],
        [ 0,  8, 16, 24],
        [ 0, 12, 24, 36],
        [ 0, 16, 32, 48]]])

In [61]:
np.fromfunction(lambda i,j,k : i*j*k, (5,5,3), dtype= int)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4],
        [ 0,  3,  6],
        [ 0,  4,  8]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8],
        [ 0,  6, 12],
        [ 0,  8, 16]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12],
        [ 0,  9, 18],
        [ 0, 12, 24]],

       [[ 0,  0,  0],
        [ 0,  4,  8],
        [ 0,  8, 16],
        [ 0, 12, 24],
        [ 0, 16, 32]]])

In [62]:
np.fromfunction(lambda i,j,k : i*j*k, (5,5,2), dtype= int)

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  1],
        [ 0,  2],
        [ 0,  3],
        [ 0,  4]],

       [[ 0,  0],
        [ 0,  2],
        [ 0,  4],
        [ 0,  6],
        [ 0,  8]],

       [[ 0,  0],
        [ 0,  3],
        [ 0,  6],
        [ 0,  9],
        [ 0, 12]],

       [[ 0,  0],
        [ 0,  4],
        [ 0,  8],
        [ 0, 12],
        [ 0, 16]]])

In [63]:
np.fromfunction(lambda i,j,k : i*j*k, (5,4,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16],
        [ 0,  6, 12, 18, 24]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  3,  6,  9, 12],
        [ 0,  6, 12, 18, 24],
        [ 0,  9, 18, 27, 36]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  4,  8, 12, 16],
        [ 0,  8, 16, 24, 32],
        [ 0, 12, 24, 36, 48]]])

In [64]:
np.fromfunction(lambda i,j,k : i*j*k, (5,3,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  3,  6,  9, 12],
        [ 0,  6, 12, 18, 24]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  4,  8, 12, 16],
        [ 0,  8, 16, 24, 32]]])

In [65]:
np.fromfunction(lambda i,j,k : i*j*k, (5,2,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  3,  6,  9, 12]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  4,  8, 12, 16]]])

In [66]:
np.fromfunction(lambda i,j,k : i*j*k, (4,5,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16],
        [ 0,  6, 12, 18, 24],
        [ 0,  8, 16, 24, 32]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  3,  6,  9, 12],
        [ 0,  6, 12, 18, 24],
        [ 0,  9, 18, 27, 36],
        [ 0, 12, 24, 36, 48]]])

In [67]:
np.fromfunction(lambda i,j,k : i*j*k, (3,5,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16],
        [ 0,  6, 12, 18, 24],
        [ 0,  8, 16, 24, 32]]])

In [68]:
np.fromfunction(lambda i,j,k : i*j*k, (2,5,5), dtype= int)

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16]]])

In [69]:
np.fromfunction(lambda i,j,k : i*j*k, (1,5,5), dtype= int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [70]:
np.fromfunction(lambda i,j,k,l : i*j*k*l, (2,1,5,5), dtype= int)

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [72]:
np.fromfunction(lambda i,j,k,l : i+j+k+l, (2,1,5,5), dtype= int)

array([[[[0, 1, 2, 3, 4],
         [1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6],
         [3, 4, 5, 6, 7],
         [4, 5, 6, 7, 8]]],


       [[[1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6],
         [3, 4, 5, 6, 7],
         [4, 5, 6, 7, 8],
         [5, 6, 7, 8, 9]]]])

In [74]:
np.fromfunction(lambda i,j,k,l,m : i+j+k+l+m, (2,2,1,5,5), dtype= int)

array([[[[[ 0,  1,  2,  3,  4],
          [ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8]]],


        [[[ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8],
          [ 5,  6,  7,  8,  9]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8],
          [ 5,  6,  7,  8,  9]]],


        [[[ 2,  3,  4,  5,  6],
          [ 3,  4,  5,  6,  7],
          [ 4,  5,  6,  7,  8],
          [ 5,  6,  7,  8,  9],
          [ 6,  7,  8,  9, 10]]]]])

In [79]:
np.fromfunction(lambda i,j,k,l,m : i+j+k+l+m, (2,2,1,2,2), dtype= int)

array([[[[[0, 1],
          [1, 2]]],


        [[[1, 2],
          [2, 3]]]],



       [[[[1, 2],
          [2, 3]]],


        [[[2, 3],
          [3, 4]]]]])

In [83]:
c=np.fromfunction(lambda i,j,k : i*j*k, (4,3,2), dtype= int)

In [84]:
c.ndim
# number of dimension 

3

In [85]:
c.size
# number of elements

24

In [87]:
c.shape


(4, 3, 2)

In [88]:
c.dtype

dtype('int32')

In [ ]:
# Try to prepare a dataframe where you have to create a 100 to 1000 or 100000 number of records.

In [ ]:
# conver c into a dataframe 
# data frame is a 2-D matrix

In [89]:
c

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [90]:
pd.DataFrame(c)     # convert only if the data is in 2 -D

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [91]:
c=np.fromfunction(lambda i,j : i*j, (3,2), dtype= int)

In [92]:
pd.DataFrame(c)

0  1
0  0  0
1  0  1
2  0  2

In [ ]:
###################### RANDOM FUNCTION###############

In [93]:
np.random.rand(100,4)

array([[0.24115093, 0.02326611, 0.5113387 , 0.07011726],
       [0.20008064, 0.43483917, 0.37193906, 0.39574168],
       [0.42915777, 0.14938773, 0.74977965, 0.54021576],
       [0.60150899, 0.75652877, 0.78294883, 0.6300589 ],
       [0.85772244, 0.2881334 , 0.23554753, 0.01760707],
       [0.70198924, 0.06144982, 0.00657786, 0.58922524],
       [0.13606268, 0.34498577, 0.55345194, 0.34658336],
       [0.12006597, 0.7628584 , 0.38149004, 0.25301613],
       [0.51690126, 0.28360498, 0.58606571, 0.95260283],
       [0.47724719, 0.65411171, 0.44142224, 0.90994918],
       [0.14150428, 0.36855475, 0.94892718, 0.23630802],
       [0.96648988, 0.62881734, 0.54059459, 0.77234901],
       [0.88651513, 0.7314672 , 0.15964645, 0.00742004],
       [0.9270502 , 0.00282777, 0.89403969, 0.86743459],
       [0.23410276, 0.361877  , 0.48733025, 0.78449965],
       [0.79905856, 0.0411883 , 0.48618811, 0.80107421],
       [0.50953842, 0.35011246, 0.84675011, 0.79442886],
       [0.83067747, 0.08147025,

In [94]:
np.random.randint(4,5)

4

In [95]:
np.random.randint(4,10
                 )

7

In [98]:
np.random.randint(4,50)

27

In [103]:
np.random.randn(4,5) # With normal distribution , AVG = 0 and SD = 1
# all the mean of the data is 0 and SD 1

array([[-0.48321652,  1.26584183,  1.17201026, -0.99365699, -0.64779946],
       [-0.56068225,  0.31373143,  1.30795134, -0.77956125, -0.04500432],
       [-0.30366676,  0.51700406,  0.54062569, -1.64570845,  1.70623347],
       [ 1.85261511,  2.08154465,  0.42878175,  0.6829379 , -0.66323727]])

In [104]:
 pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.106690  1.187315  0.660400 -1.310044 -1.944340
1 -0.647578 -0.843933 -0.230632 -0.240301 -0.299097
2 -0.915367  0.520200  1.461699  0.421395  0.575100
3  0.577531  0.238836  0.265853  1.414515 -0.420043

In [107]:
n = pd.DataFrame(np.random.randn(4,5))


In [ ]:
############### CONVERT OF CHANGED THE DIMENSION OF A DATASET################3


In [108]:
c=np.fromfunction(lambda i,j,k : i*j*k, (4,3,2), dtype= int)

In [109]:
C

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [110]:
C.ndim

3

In [112]:
C.size

24

In [113]:
C.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [114]:
C.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [115]:
C.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [ ]:
# what ever will be the fraction of the size will be able to reshape accordingly 

In [118]:
c=C.reshape(3,8)

In [119]:
pd.DataFrame(c)

0  1  2  3  4  5  6  7
0  0  0  0  0  0  0  0  0
1  0  1  0  2  0  0  0  2
2  0  4  0  0  0  3  0  6

In [ ]:
# How to convert into 4 D

In [120]:
c=np.fromfunction(lambda i,j,k : i*j*k, (4,3,2), dtype= int)

In [121]:
c

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [122]:
c.reshape(2,2,3,2)

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1],
         [0, 2]]],


       [[[0, 0],
         [0, 2],
         [0, 4]],

        [[0, 0],
         [0, 3],
         [0, 6]]]])

In [ ]:
# reshape is function used in image processing 

In [123]:
c.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [125]:
c.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [126]:
c.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [127]:
c.reshape(3,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [128]:
c.reshape(6,-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [129]:
c.reshape(6,-13513546)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [130]:
c.reshape(2,4,-13513546)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [ ]:
######################### RANGE ################################

# Equivalent function of a range function arange in numpy 

In [131]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [132]:
list(range(4,11))

[4, 5, 6, 7, 8, 9, 10]

In [134]:
list(range(4,50,3))

[4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [135]:
list(range(4,50,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# in the numpy we have arange

In [140]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [141]:
list(np.arange(4,10,0.2),)

[4.0,
 4.2,
 4.4,
 4.6000000000000005,
 4.800000000000001,
 5.000000000000001,
 5.200000000000001,
 5.400000000000001,
 5.600000000000001,
 5.800000000000002,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.800000000000003,
 8.000000000000004,
 8.200000000000003,
 8.400000000000004,
 8.600000000000005,
 8.800000000000004,
 9.000000000000004,
 9.200000000000005,
 9.400000000000006,
 9.600000000000005,
 9.800000000000004]

In [142]:
np.arange(4,10.5,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [143]:
a2 = np.arange(4,10.5,0.2)

In [144]:
a2

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [145]:
a1[1:5] # slicing operation is same

array([4., 5., 6., 7.])

In [146]:
arr = np.random.rand(4,5)

In [147]:
arr

array([[0.63722625, 0.70875723, 0.83586845, 0.4001449 , 0.15863871],
       [0.80847805, 0.74306971, 0.75977923, 0.88137933, 0.27006904],
       [0.11809809, 0.14126829, 0.04768812, 0.52202281, 0.31451514],
       [0.14054591, 0.00871907, 0.61939236, 0.20204671, 0.85522625]])

In [ ]:
# Will you be able to extract all the data greater than 0.5 ? 
# operations is similar to pandas

In [148]:
arr>0.5

array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True, False],
       [False, False, False,  True, False],
       [False, False,  True, False,  True]])

In [149]:
arr[arr>0.5]

array([0.63722625, 0.70875723, 0.83586845, 0.80847805, 0.74306971,
       0.75977923, 0.88137933, 0.52202281, 0.61939236, 0.85522625])

In [150]:
arr

array([[0.63722625, 0.70875723, 0.83586845, 0.4001449 , 0.15863871],
       [0.80847805, 0.74306971, 0.75977923, 0.88137933, 0.27006904],
       [0.11809809, 0.14126829, 0.04768812, 0.52202281, 0.31451514],
       [0.14054591, 0.00871907, 0.61939236, 0.20204671, 0.85522625]])

In [153]:
arr[1][2]

0.7597792282482485

In [154]:
arr[2][2]

0.047688123248070036

In [155]:
arr[[1,2], [2]]

array([0.75977923, 0.04768812])

In [157]:
arr1 = np.random.rand(8,5)
arr1

array([[0.17779652, 0.04125589, 0.34369808, 0.60382027, 0.33448788],
       [0.86420505, 0.62890777, 0.22606432, 0.40307971, 0.80156945],
       [0.09750113, 0.82318213, 0.43784276, 0.42944996, 0.38000397],
       [0.91425283, 0.41480033, 0.03338005, 0.56803517, 0.61402082],
       [0.85151681, 0.7398293 , 0.29964903, 0.39222665, 0.61806892],
       [0.22031214, 0.59430264, 0.10132858, 0.77413711, 0.56125959],
       [0.25486158, 0.60043489, 0.22017891, 0.97904908, 0.63456155],
       [0.76527209, 0.90636862, 0.11707297, 0.99168569, 0.18247207]])

In [161]:
arr1[1:8,0:3]

array([[0.86420505, 0.62890777, 0.22606432],
       [0.09750113, 0.82318213, 0.43784276],
       [0.91425283, 0.41480033, 0.03338005],
       [0.85151681, 0.7398293 , 0.29964903],
       [0.22031214, 0.59430264, 0.10132858],
       [0.25486158, 0.60043489, 0.22017891],
       [0.76527209, 0.90636862, 0.11707297]])

In [163]:
arr1[1:6,[0,1,2]]

array([[0.86420505, 0.62890777, 0.22606432],
       [0.09750113, 0.82318213, 0.43784276],
       [0.91425283, 0.41480033, 0.03338005],
       [0.85151681, 0.7398293 , 0.29964903],
       [0.22031214, 0.59430264, 0.10132858]])

In [164]:
arr1

array([[0.17779652, 0.04125589, 0.34369808, 0.60382027, 0.33448788],
       [0.86420505, 0.62890777, 0.22606432, 0.40307971, 0.80156945],
       [0.09750113, 0.82318213, 0.43784276, 0.42944996, 0.38000397],
       [0.91425283, 0.41480033, 0.03338005, 0.56803517, 0.61402082],
       [0.85151681, 0.7398293 , 0.29964903, 0.39222665, 0.61806892],
       [0.22031214, 0.59430264, 0.10132858, 0.77413711, 0.56125959],
       [0.25486158, 0.60043489, 0.22017891, 0.97904908, 0.63456155],
       [0.76527209, 0.90636862, 0.11707297, 0.99168569, 0.18247207]])

In [ ]:
# Replace the very first data to another data 

In [166]:
arr1[0][0]

0.17779651525140916

In [167]:
arr1[0][0] = 100

In [168]:
arr1

array([[1.00000000e+02, 4.12558867e-02, 3.43698083e-01, 6.03820273e-01,
        3.34487877e-01],
       [8.64205051e-01, 6.28907774e-01, 2.26064318e-01, 4.03079711e-01,
        8.01569448e-01],
       [9.75011333e-02, 8.23182135e-01, 4.37842761e-01, 4.29449956e-01,
        3.80003972e-01],
       [9.14252831e-01, 4.14800332e-01, 3.33800475e-02, 5.68035174e-01,
        6.14020818e-01],
       [8.51516805e-01, 7.39829304e-01, 2.99649034e-01, 3.92226650e-01,
        6.18068922e-01],
       [2.20312141e-01, 5.94302641e-01, 1.01328575e-01, 7.74137115e-01,
        5.61259587e-01],
       [2.54861581e-01, 6.00434893e-01, 2.20178914e-01, 9.79049085e-01,
        6.34561553e-01],
       [7.65272086e-01, 9.06368624e-01, 1.17072974e-01, 9.91685693e-01,
        1.82472073e-01]])

In [173]:
f = np.array([[1,2],[3,4]])
g = np.array([[2,3],[4,5]])

In [174]:
f

array([[1, 2],
       [3, 4]])

In [175]:
g

array([[2, 3],
       [4, 5]])

In [176]:
f*g  ## ELEMENT WISE MULTIPLICATION 

array([[ 2,  6],
       [12, 20]])

In [ ]:
################## MATRIX MULTIPLICATION #########################
# IT WILL BE USED A LOT IN DEEP LEARNING 
# DARK NET
# ALEX NET
# RESNET 100 , 150 
# ETC

In [177]:
f@g

array([[10, 13],
       [22, 29]])

In [178]:
h = f@g

In [179]:
h/0

<ipython-input-179-f5f7e40c6531>:1: RuntimeWarning: divide by zero encountered in true_divide
  h/0


array([[inf, inf],
       [inf, inf]])